# This file is intended to be used only in TI's internal Continuous Integration
# (CI) system and will not function outside.
services:
  zephyr:
    # Set to current user
    build:
      context: ../../../
      dockerfile: zephyr/etc/docker/Dockerfile
    # Same as service name
    hostname: zephyr
    environment:
      - ATLASSIAN_PASSWORD
      - ATLASSIAN_USER
      - BITBUCKET_AUTH_TOKEN
      - CONFLUENCE_AUTH_TOKEN
      - JIRA_AUTH_TOKEN
      # TERM variable adds color to interactive shells
      - TERM=xterm-256color
      - TESTLINK_AUTH_TOKEN
    volumes:
      # This places us in the general Jenkins workspace, where zephyr
      # is cloned to a subfolder
      - ../../../:/project
