# This file is intended to be used only in TI's internal Continuous Integration
# (CI) system and will not function outside.
version: '3.7'
services:
  zephyr:
    volumes:
      - /dev/serial:/dev/serial:ro
    devices:
      - /dev/bus:/dev/bus
      - /dev/ttyACM0:/dev/ttyACM0
