## System and OS related flags
# Logging flag
CONFIG_LOG=y
# Console print flags
CONFIG_UART_CONSOLE=y
CONFIG_PRINTK=y
CONFIG_CONSOLE=y
# Settings flag for storage of keys and DB related info
CONFIG_SETTINGS=y
# Heap pool size should e given for allocation of memory
CONFIG_HEAP_MEM_POOL_SIZE=512
# CLI shell support
CONFIG_SHELL=y

## BT flags
CONFIG_BT=y
CONFIG_BT_BROADCASTER=y
CONFIG_BT_OBSERVER=y
# Extended ADV flag
CONFIG_BT_EXT_ADV=y
# Periodic ADV flag
CONFIG_BT_PER_ADV=y
# Encrypted ADV flag
CONFIG_BT_EAD=y
# Default device name
CONFIG_BT_DEVICE_NAME="esl_zephyr"
# Max connections
CONFIG_BT_MAX_CONN=2
# Keep pairing capacity at least as large as the total retained tag count.
CONFIG_BT_MAX_PAIRED=4
# SMP flag
CONFIG_BT_SMP=y

# Disable 2M PHY
CONFIG_BT_PHY_UPDATE=n
# Disable coded PHY
CONFIG_BT_CTLR_PHY_CODED=n

## ESL AP BT flags
CONFIG_BT_CENTRAL=y
CONFIG_BT_REMOTE_INFO=y
CONFIG_BT_GATT_CLIENT=y
# Periodic ADV response flag
CONFIG_BT_PER_ADV_RSP=y
# PAST sender flag
CONFIG_BT_PER_ADV_SYNC_TRANSFER_SENDER=y

## OTS client flags
CONFIG_BT_OTS=y
CONFIG_BT_OTS_CLIENT=y

# This example requires more workqueue stack
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=8192

## ESL AP flags
CONFIG_BT_ESL_AP=y
CONFIG_BT_ESL_SEPARATE_KEY_PER_GROUP=n
CONFIG_BT_ESL_MAX_SENSOR_SUPPORTED=2
CONFIG_BT_ESL_MAX_LED_SUPPORTED=2
CONFIG_BT_ESL_MAX_IMAGE_SUPPORTED=2
CONFIG_BT_ESL_MAX_DISPLAY_SUPPORTED=2
CONFIG_BT_ESL_MAX_GROUPS_SUPPORTED=1
CONFIG_BT_ESL_MAX_ESL_TAGS_SUPPORTED=4
### ESL Debug Flags
CONFIG_ESL_PL_DEBUG_TO_CONSOLE=n
CONFIG_ESL_AP_LOG=y
